/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.uwaterloo.esg.rvtool.jni.libconfig;

public final class config_error_t {
  public final static config_error_t CONFIG_ERR_NONE = new config_error_t("CONFIG_ERR_NONE", libconfigJNI.CONFIG_ERR_NONE_get());
  public final static config_error_t CONFIG_ERR_FILE_IO = new config_error_t("CONFIG_ERR_FILE_IO", libconfigJNI.CONFIG_ERR_FILE_IO_get());
  public final static config_error_t CONFIG_ERR_PARSE = new config_error_t("CONFIG_ERR_PARSE", libconfigJNI.CONFIG_ERR_PARSE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static config_error_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + config_error_t.class + " with value " + swigValue);
  }

  private config_error_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private config_error_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private config_error_t(String swigName, config_error_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static config_error_t[] swigValues = { CONFIG_ERR_NONE, CONFIG_ERR_FILE_IO, CONFIG_ERR_PARSE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

