/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.uwaterloo.esg.rvtool.jni.libconfig;

public class config_setting_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected config_setting_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(config_setting_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libconfigJNI.delete_config_setting_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    libconfigJNI.config_setting_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libconfigJNI.config_setting_t_name_get(swigCPtr, this);
  }

  public void setType(short value) {
    libconfigJNI.config_setting_t_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return libconfigJNI.config_setting_t_type_get(swigCPtr, this);
  }

  public void setFormat(short value) {
    libconfigJNI.config_setting_t_format_set(swigCPtr, this, value);
  }

  public short getFormat() {
    return libconfigJNI.config_setting_t_format_get(swigCPtr, this);
  }

  public void setValue(config_value_t value) {
    libconfigJNI.config_setting_t_value_set(swigCPtr, this, config_value_t.getCPtr(value), value);
  }

  public config_value_t getValue() {
    long cPtr = libconfigJNI.config_setting_t_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new config_value_t(cPtr, false);
  }

  public void setParent(config_setting_t value) {
    libconfigJNI.config_setting_t_parent_set(swigCPtr, this, config_setting_t.getCPtr(value), value);
  }

  public config_setting_t getParent() {
    long cPtr = libconfigJNI.config_setting_t_parent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public void setConfig(config_t value) {
    libconfigJNI.config_setting_t_config_set(swigCPtr, this, config_t.getCPtr(value), value);
  }

  public config_t getConfig() {
    long cPtr = libconfigJNI.config_setting_t_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new config_t(cPtr, false);
  }

  public void setHook(SWIGTYPE_p_void value) {
    libconfigJNI.config_setting_t_hook_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getHook() {
    long cPtr = libconfigJNI.config_setting_t_hook_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLine(long value) {
    libconfigJNI.config_setting_t_line_set(swigCPtr, this, value);
  }

  public long getLine() {
    return libconfigJNI.config_setting_t_line_get(swigCPtr, this);
  }

  public void setFile(String value) {
    libconfigJNI.config_setting_t_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return libconfigJNI.config_setting_t_file_get(swigCPtr, this);
  }

  public config_setting_t() {
    this(libconfigJNI.new_config_setting_t(), true);
  }

}
