/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.uwaterloo.esg.rvtool.jni.libconfig;

public class config_value_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected config_value_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(config_value_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libconfigJNI.delete_config_value_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIval(int value) {
    libconfigJNI.config_value_t_ival_set(swigCPtr, this, value);
  }

  public int getIval() {
    return libconfigJNI.config_value_t_ival_get(swigCPtr, this);
  }

  public void setLlval(long value) {
    libconfigJNI.config_value_t_llval_set(swigCPtr, this, value);
  }

  public long getLlval() {
    return libconfigJNI.config_value_t_llval_get(swigCPtr, this);
  }

  public void setFval(double value) {
    libconfigJNI.config_value_t_fval_set(swigCPtr, this, value);
  }

  public double getFval() {
    return libconfigJNI.config_value_t_fval_get(swigCPtr, this);
  }

  public void setSval(String value) {
    libconfigJNI.config_value_t_sval_set(swigCPtr, this, value);
  }

  public String getSval() {
    return libconfigJNI.config_value_t_sval_get(swigCPtr, this);
  }

  public void setList(config_list_t value) {
    libconfigJNI.config_value_t_list_set(swigCPtr, this, config_list_t.getCPtr(value), value);
  }

  public config_list_t getList() {
    long cPtr = libconfigJNI.config_value_t_list_get(swigCPtr, this);
    return (cPtr == 0) ? null : new config_list_t(cPtr, false);
  }

  public config_value_t() {
    this(libconfigJNI.new_config_value_t(), true);
  }

}
