/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.uwaterloo.esg.rvtool.jni.libconfig;

public interface libconfigConstants {
  public final static int LIBCONFIG_VER_MAJOR = libconfigJNI.LIBCONFIG_VER_MAJOR_get();
  public final static int LIBCONFIG_VER_MINOR = libconfigJNI.LIBCONFIG_VER_MINOR_get();
  public final static int LIBCONFIG_VER_REVISION = libconfigJNI.LIBCONFIG_VER_REVISION_get();
  public final static int CONFIG_TYPE_NONE = libconfigJNI.CONFIG_TYPE_NONE_get();
  public final static int CONFIG_TYPE_GROUP = libconfigJNI.CONFIG_TYPE_GROUP_get();
  public final static int CONFIG_TYPE_INT = libconfigJNI.CONFIG_TYPE_INT_get();
  public final static int CONFIG_TYPE_INT64 = libconfigJNI.CONFIG_TYPE_INT64_get();
  public final static int CONFIG_TYPE_FLOAT = libconfigJNI.CONFIG_TYPE_FLOAT_get();
  public final static int CONFIG_TYPE_STRING = libconfigJNI.CONFIG_TYPE_STRING_get();
  public final static int CONFIG_TYPE_BOOL = libconfigJNI.CONFIG_TYPE_BOOL_get();
  public final static int CONFIG_TYPE_ARRAY = libconfigJNI.CONFIG_TYPE_ARRAY_get();
  public final static int CONFIG_TYPE_LIST = libconfigJNI.CONFIG_TYPE_LIST_get();
  public final static int CONFIG_FORMAT_DEFAULT = libconfigJNI.CONFIG_FORMAT_DEFAULT_get();
  public final static int CONFIG_FORMAT_HEX = libconfigJNI.CONFIG_FORMAT_HEX_get();
  public final static int CONFIG_OPTION_AUTOCONVERT = libconfigJNI.CONFIG_OPTION_AUTOCONVERT_get();
  public final static int CONFIG_TRUE = libconfigJNI.CONFIG_TRUE_get();
  public final static int CONFIG_FALSE = libconfigJNI.CONFIG_FALSE_get();
}
