/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ca.uwaterloo.esg.rvtool.jni.libconfig;

public class libconfig implements libconfigConstants {
  public static int config_read(config_t config, SWIGTYPE_p_FILE stream) {
    return libconfigJNI.config_read(config_t.getCPtr(config), config, SWIGTYPE_p_FILE.getCPtr(stream));
  }

  public static void config_write(config_t config, SWIGTYPE_p_FILE stream) {
    libconfigJNI.config_write(config_t.getCPtr(config), config, SWIGTYPE_p_FILE.getCPtr(stream));
  }

  public static void config_set_default_format(config_t config, short format) {
    libconfigJNI.config_set_default_format(config_t.getCPtr(config), config, format);
  }

  public static void config_set_auto_convert(config_t config, int flag) {
    libconfigJNI.config_set_auto_convert(config_t.getCPtr(config), config, flag);
  }

  public static int config_get_auto_convert(config_t config) {
    return libconfigJNI.config_get_auto_convert(config_t.getCPtr(config), config);
  }

  public static int config_read_string(config_t config, String str) {
    return libconfigJNI.config_read_string(config_t.getCPtr(config), config, str);
  }

  public static int config_read_file(config_t config, String filename) {
    return libconfigJNI.config_read_file(config_t.getCPtr(config), config, filename);
  }

  public static int config_write_file(config_t config, String filename) {
    return libconfigJNI.config_write_file(config_t.getCPtr(config), config, filename);
  }

  public static void config_set_destructor(config_t config, SWIGTYPE_p_f_p_void__void destructor) {
    libconfigJNI.config_set_destructor(config_t.getCPtr(config), config, SWIGTYPE_p_f_p_void__void.getCPtr(destructor));
  }

  public static void config_set_include_dir(config_t config, String include_dir) {
    libconfigJNI.config_set_include_dir(config_t.getCPtr(config), config, include_dir);
  }

  public static void config_init(config_t config) {
    libconfigJNI.config_init(config_t.getCPtr(config), config);
  }

  public static void config_destroy(config_t config) {
    libconfigJNI.config_destroy(config_t.getCPtr(config), config);
  }

  public static int config_setting_get_int(config_setting_t setting) {
    return libconfigJNI.config_setting_get_int(config_setting_t.getCPtr(setting), setting);
  }

  public static long config_setting_get_int64(config_setting_t setting) {
    return libconfigJNI.config_setting_get_int64(config_setting_t.getCPtr(setting), setting);
  }

  public static double config_setting_get_float(config_setting_t setting) {
    return libconfigJNI.config_setting_get_float(config_setting_t.getCPtr(setting), setting);
  }

  public static int config_setting_get_bool(config_setting_t setting) {
    return libconfigJNI.config_setting_get_bool(config_setting_t.getCPtr(setting), setting);
  }

  public static String config_setting_get_string(config_setting_t setting) {
    return libconfigJNI.config_setting_get_string(config_setting_t.getCPtr(setting), setting);
  }

  public static int config_setting_lookup_int(config_setting_t setting, String name, SWIGTYPE_p_int value) {
    return libconfigJNI.config_setting_lookup_int(config_setting_t.getCPtr(setting), setting, name, SWIGTYPE_p_int.getCPtr(value));
  }

  public static int config_setting_lookup_int64(config_setting_t setting, String name, SWIGTYPE_p_long_long value) {
    return libconfigJNI.config_setting_lookup_int64(config_setting_t.getCPtr(setting), setting, name, SWIGTYPE_p_long_long.getCPtr(value));
  }

  public static int config_setting_lookup_float(config_setting_t setting, String name, SWIGTYPE_p_double value) {
    return libconfigJNI.config_setting_lookup_float(config_setting_t.getCPtr(setting), setting, name, SWIGTYPE_p_double.getCPtr(value));
  }

  public static int config_setting_lookup_bool(config_setting_t setting, String name, SWIGTYPE_p_int value) {
    return libconfigJNI.config_setting_lookup_bool(config_setting_t.getCPtr(setting), setting, name, SWIGTYPE_p_int.getCPtr(value));
  }

  public static int config_setting_lookup_string(config_setting_t setting, String name, String[] value) {
    return libconfigJNI.config_setting_lookup_string(config_setting_t.getCPtr(setting), setting, name, value);
  }

  public static int config_setting_set_int(config_setting_t setting, int value) {
    return libconfigJNI.config_setting_set_int(config_setting_t.getCPtr(setting), setting, value);
  }

  public static int config_setting_set_int64(config_setting_t setting, long value) {
    return libconfigJNI.config_setting_set_int64(config_setting_t.getCPtr(setting), setting, value);
  }

  public static int config_setting_set_float(config_setting_t setting, double value) {
    return libconfigJNI.config_setting_set_float(config_setting_t.getCPtr(setting), setting, value);
  }

  public static int config_setting_set_bool(config_setting_t setting, int value) {
    return libconfigJNI.config_setting_set_bool(config_setting_t.getCPtr(setting), setting, value);
  }

  public static int config_setting_set_string(config_setting_t setting, String value) {
    return libconfigJNI.config_setting_set_string(config_setting_t.getCPtr(setting), setting, value);
  }

  public static int config_setting_set_format(config_setting_t setting, short format) {
    return libconfigJNI.config_setting_set_format(config_setting_t.getCPtr(setting), setting, format);
  }

  public static short config_setting_get_format(config_setting_t setting) {
    return libconfigJNI.config_setting_get_format(config_setting_t.getCPtr(setting), setting);
  }

  public static int config_setting_get_int_elem(config_setting_t setting, int idx) {
    return libconfigJNI.config_setting_get_int_elem(config_setting_t.getCPtr(setting), setting, idx);
  }

  public static long config_setting_get_int64_elem(config_setting_t setting, int idx) {
    return libconfigJNI.config_setting_get_int64_elem(config_setting_t.getCPtr(setting), setting, idx);
  }

  public static double config_setting_get_float_elem(config_setting_t setting, int idx) {
    return libconfigJNI.config_setting_get_float_elem(config_setting_t.getCPtr(setting), setting, idx);
  }

  public static int config_setting_get_bool_elem(config_setting_t setting, int idx) {
    return libconfigJNI.config_setting_get_bool_elem(config_setting_t.getCPtr(setting), setting, idx);
  }

  public static String config_setting_get_string_elem(config_setting_t setting, int idx) {
    return libconfigJNI.config_setting_get_string_elem(config_setting_t.getCPtr(setting), setting, idx);
  }

  public static config_setting_t config_setting_set_int_elem(config_setting_t setting, int idx, int value) {
    long cPtr = libconfigJNI.config_setting_set_int_elem(config_setting_t.getCPtr(setting), setting, idx, value);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_set_int64_elem(config_setting_t setting, int idx, long value) {
    long cPtr = libconfigJNI.config_setting_set_int64_elem(config_setting_t.getCPtr(setting), setting, idx, value);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_set_float_elem(config_setting_t setting, int idx, double value) {
    long cPtr = libconfigJNI.config_setting_set_float_elem(config_setting_t.getCPtr(setting), setting, idx, value);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_set_bool_elem(config_setting_t setting, int idx, int value) {
    long cPtr = libconfigJNI.config_setting_set_bool_elem(config_setting_t.getCPtr(setting), setting, idx, value);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_set_string_elem(config_setting_t setting, int idx, String value) {
    long cPtr = libconfigJNI.config_setting_set_string_elem(config_setting_t.getCPtr(setting), setting, idx, value);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static int config_setting_index(config_setting_t setting) {
    return libconfigJNI.config_setting_index(config_setting_t.getCPtr(setting), setting);
  }

  public static int config_setting_length(config_setting_t setting) {
    return libconfigJNI.config_setting_length(config_setting_t.getCPtr(setting), setting);
  }

  public static config_setting_t config_setting_get_elem(config_setting_t setting, long idx) {
    long cPtr = libconfigJNI.config_setting_get_elem(config_setting_t.getCPtr(setting), setting, idx);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_get_member(config_setting_t setting, String name) {
    long cPtr = libconfigJNI.config_setting_get_member(config_setting_t.getCPtr(setting), setting, name);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_setting_add(config_setting_t parent, String name, int type) {
    long cPtr = libconfigJNI.config_setting_add(config_setting_t.getCPtr(parent), parent, name, type);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static int config_setting_remove(config_setting_t parent, String name) {
    return libconfigJNI.config_setting_remove(config_setting_t.getCPtr(parent), parent, name);
  }

  public static int config_setting_remove_elem(config_setting_t parent, long idx) {
    return libconfigJNI.config_setting_remove_elem(config_setting_t.getCPtr(parent), parent, idx);
  }

  public static void config_setting_set_hook(config_setting_t setting, SWIGTYPE_p_void hook) {
    libconfigJNI.config_setting_set_hook(config_setting_t.getCPtr(setting), setting, SWIGTYPE_p_void.getCPtr(hook));
  }

  public static config_setting_t config_lookup(config_t config, String path) {
    long cPtr = libconfigJNI.config_lookup(config_t.getCPtr(config), config, path);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static config_setting_t config_lookup_from(config_setting_t setting, String path) {
    long cPtr = libconfigJNI.config_lookup_from(config_setting_t.getCPtr(setting), setting, path);
    return (cPtr == 0) ? null : new config_setting_t(cPtr, false);
  }

  public static int config_lookup_int(config_t config, String path, SWIGTYPE_p_int value) {
    return libconfigJNI.config_lookup_int(config_t.getCPtr(config), config, path, SWIGTYPE_p_int.getCPtr(value));
  }

  public static int config_lookup_int64(config_t config, String path, SWIGTYPE_p_long_long value) {
    return libconfigJNI.config_lookup_int64(config_t.getCPtr(config), config, path, SWIGTYPE_p_long_long.getCPtr(value));
  }

  public static int config_lookup_float(config_t config, String path, SWIGTYPE_p_double value) {
    return libconfigJNI.config_lookup_float(config_t.getCPtr(config), config, path, SWIGTYPE_p_double.getCPtr(value));
  }

  public static int config_lookup_bool(config_t config, String path, SWIGTYPE_p_int value) {
    return libconfigJNI.config_lookup_bool(config_t.getCPtr(config), config, path, SWIGTYPE_p_int.getCPtr(value));
  }

  public static int config_lookup_string(config_t config, String path, String[] value) {
    return libconfigJNI.config_lookup_string(config_t.getCPtr(config), config, path, value);
  }

}
