/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "libconfig.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_LIBCONFIG_1VER_1MAJOR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_LIBCONFIG_1VER_1MINOR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_LIBCONFIG_1VER_1REVISION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1GROUP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1INT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1INT64_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1FLOAT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1BOOL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1ARRAY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TYPE_1LIST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1FORMAT_1DEFAULT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1FORMAT_1HEX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1OPTION_1AUTOCONVERT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0x01);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1TRUE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((1));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1FALSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((0));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1ival_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ival = arg2;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1ival_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  result = (int) ((arg1)->ival);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1llval_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  long long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  arg2 = (long long)jarg2; 
  if (arg1) (arg1)->llval = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1llval_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  result = (long long) ((arg1)->llval);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1fval_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->fval = arg2;
}


SWIGEXPORT jdouble JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1fval_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  result = (double) ((arg1)->fval);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1sval_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->sval);
    if (arg2) {
      arg1->sval = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->sval, (const char *)arg2);
    } else {
      arg1->sval = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1sval_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  result = (char *) ((arg1)->sval);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1list_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  struct config_list_t *arg2 = (struct config_list_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(union config_value_t **)&jarg1; 
  arg2 = *(struct config_list_t **)&jarg2; 
  if (arg1) (arg1)->list = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1value_1t_1list_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  struct config_list_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(union config_value_t **)&jarg1; 
  result = (struct config_list_t *) ((arg1)->list);
  *(struct config_list_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_new_1config_1value_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  union config_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (union config_value_t *)calloc(1, sizeof(union config_value_t));
  *(union config_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_delete_1config_1value_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  union config_value_t *arg1 = (union config_value_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(union config_value_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = (short)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jshort JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (short) ((arg1)->type);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1format_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = (short)jarg2; 
  if (arg1) (arg1)->format = arg2;
}


SWIGEXPORT jshort JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1format_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (short) ((arg1)->format);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  config_value_t *arg2 = (config_value_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = *(config_value_t **)&jarg2; 
  if (arg1) (arg1)->value = *arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  config_value_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (config_value_t *)& ((arg1)->value);
  *(config_value_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1parent_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  struct config_setting_t *arg2 = (struct config_setting_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = *(struct config_setting_t **)&jarg2; 
  if (arg1) (arg1)->parent = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1parent_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  struct config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (struct config_setting_t *) ((arg1)->parent);
  *(struct config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1config_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  struct config_t *arg2 = (struct config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = *(struct config_t **)&jarg2; 
  if (arg1) (arg1)->config = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1config_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  struct config_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (struct config_t *) ((arg1)->config);
  *(struct config_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1hook_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->hook = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1hook_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (void *) ((arg1)->hook);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1line_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->line = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1line_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (unsigned int) ((arg1)->line);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1file_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->file = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->file, (const char *)arg2);
    } else {
      arg1->file = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1t_1file_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_setting_t **)&jarg1; 
  result = (char *) ((arg1)->file);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_new_1config_1setting_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct config_setting_t *)calloc(1, sizeof(struct config_setting_t));
  *(struct config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_delete_1config_1setting_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct config_setting_t *arg1 = (struct config_setting_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct config_setting_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1ERR_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  config_error_t result;
  
  (void)jenv;
  (void)jcls;
  result = (config_error_t)CONFIG_ERR_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1ERR_1FILE_1IO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  config_error_t result;
  
  (void)jenv;
  (void)jcls;
  result = (config_error_t)CONFIG_ERR_FILE_IO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_CONFIG_1ERR_1PARSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  config_error_t result;
  
  (void)jenv;
  (void)jcls;
  result = (config_error_t)CONFIG_ERR_PARSE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1list_1t_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_list_t *arg1 = (struct config_list_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_list_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1list_1t_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_list_t *arg1 = (struct config_list_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_list_t **)&jarg1; 
  result = (unsigned int) ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1list_1t_1elements_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_list_t *arg1 = (struct config_list_t *) 0 ;
  config_setting_t **arg2 = (config_setting_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_list_t **)&jarg1; 
  arg2 = *(config_setting_t ***)&jarg2; 
  if (arg1) (arg1)->elements = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1list_1t_1elements_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_list_t *arg1 = (struct config_list_t *) 0 ;
  config_setting_t **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_list_t **)&jarg1; 
  result = (config_setting_t **) ((arg1)->elements);
  *(config_setting_t ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_new_1config_1list_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct config_list_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct config_list_t *)calloc(1, sizeof(struct config_list_t));
  *(struct config_list_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_delete_1config_1list_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct config_list_t *arg1 = (struct config_list_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct config_list_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1root_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  config_setting_t *arg2 = (config_setting_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = *(config_setting_t **)&jarg2; 
  if (arg1) (arg1)->root = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1root_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (config_setting_t *) ((arg1)->root);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1destructor_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  void (*arg2)(void *) = (void (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = *(void (**)(void *))&jarg2; 
  if (arg1) (arg1)->destructor = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1destructor_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  void (*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (void (*)(void *)) ((arg1)->destructor);
  *(void (**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1flags_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (unsigned short)jarg2; 
  if (arg1) (arg1)->flags = arg2;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1flags_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (unsigned short) ((arg1)->flags);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1tab_1width_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (unsigned short)jarg2; 
  if (arg1) (arg1)->tab_width = arg2;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1tab_1width_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (unsigned short) ((arg1)->tab_width);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1default_1format_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (short)jarg2; 
  if (arg1) (arg1)->default_format = arg2;
}


SWIGEXPORT jshort JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1default_1format_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (short) ((arg1)->default_format);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1include_1dir_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->include_dir = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->include_dir, (const char *)arg2);
    } else {
      arg1->include_dir = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1include_1dir_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (char *) ((arg1)->include_dir);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1text_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->error_text = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->error_text, (const char *)arg2);
    } else {
      arg1->error_text = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1text_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (char *) ((arg1)->error_text);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1file_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->error_file = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->error_file, (const char *)arg2);
    } else {
      arg1->error_file = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1file_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (char *) ((arg1)->error_file);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1line_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->error_line = arg2;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1line_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (int) ((arg1)->error_line);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  config_error_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (config_error_t)jarg2; 
  if (arg1) (arg1)->error_type = arg2;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1error_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  config_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (config_error_t) ((arg1)->error_type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1filenames_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  char **arg2 = (char **) 0 ;
  char *temp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    arg2 = &temp2; 
    *arg2 = 0;
  }
  if (arg1) (arg1)->filenames = (char const **)arg2;
  {
    jstring jnewstring = NULL;
    if (arg2) {
      jnewstring = (*jenv)->NewStringUTF(jenv, *arg2);
    }
    (*jenv)->SetObjectArrayElement(jenv, jarg2, 0, jnewstring); 
  }
}


SWIGEXPORT jobjectArray JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1filenames_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobjectArray jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (char **) ((arg1)->filenames);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1num_1filenames_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->num_filenames = arg2;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1t_1num_1filenames_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct config_t *arg1 = (struct config_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct config_t **)&jarg1; 
  result = (unsigned int) ((arg1)->num_filenames);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_new_1config_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct config_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct config_t *)calloc(1, sizeof(struct config_t));
  *(struct config_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_delete_1config_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct config_t *arg1 = (struct config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct config_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = *(FILE **)&jarg2; 
  result = (int)config_read(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  config_t *arg1 = (config_t *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = *(FILE **)&jarg2; 
  config_write((struct config_t const *)arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1set_1default_1format(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  config_t *arg1 = (config_t *) 0 ;
  short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = (short)jarg2; 
  config_set_default_format(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1set_1auto_1convert(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  config_t *arg1 = (config_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = (int)jarg2; 
  config_set_auto_convert(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1get_1auto_1convert(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  result = (int)config_get_auto_convert((struct config_t const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1read_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)config_read_string(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1read_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)config_read_file(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1write_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)config_write_file(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1set_1destructor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  config_t *arg1 = (config_t *) 0 ;
  void (*arg2)(void *) = (void (*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = *(void (**)(void *))&jarg2; 
  config_set_destructor(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1set_1include_1dir(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  config_set_include_dir(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  config_t *arg1 = (config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  config_init(arg1);
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  config_t *arg1 = (config_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  config_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (int)config_setting_get_int((struct config_setting_t const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (long long)config_setting_get_int64((struct config_setting_t const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (double)config_setting_get_float((struct config_setting_t const *)arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (int)config_setting_get_bool((struct config_setting_t const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (char *)config_setting_get_string((struct config_setting_t const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1lookup_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (int)config_setting_lookup_int((struct config_setting_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1lookup_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  long long *arg3 = (long long *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(long long **)&jarg3; 
  result = (int)config_setting_lookup_int64((struct config_setting_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1lookup_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 = (double *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  result = (int)config_setting_lookup_float((struct config_setting_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1lookup_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (int)config_setting_lookup_bool((struct config_setting_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1lookup_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  char *temp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = &temp3; 
    *arg3 = 0;
  }
  result = (int)config_setting_lookup_string((struct config_setting_t const *)arg1,(char const *)arg2,(char const **)arg3);
  jresult = (jint)result; 
  {
    jstring jnewstring = NULL;
    if (arg3) {
      jnewstring = (*jenv)->NewStringUTF(jenv, *arg3);
    }
    (*jenv)->SetObjectArrayElement(jenv, jarg3, 0, jnewstring); 
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)config_setting_set_int(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  long long arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (long long)jarg2; 
  result = (int)config_setting_set_int64(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  double arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (double)jarg2; 
  result = (int)config_setting_set_float(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)config_setting_set_bool(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)config_setting_set_string(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1format(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  short arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (short)jarg2; 
  result = (int)config_setting_set_format(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1format(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (short)config_setting_get_format((struct config_setting_t const *)arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1int_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)config_setting_get_int_elem((struct config_setting_t const *)arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1int64_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (long long)config_setting_get_int64_elem((struct config_setting_t const *)arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1float_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (double)config_setting_get_float_elem((struct config_setting_t const *)arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1bool_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)config_setting_get_bool_elem((struct config_setting_t const *)arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1string_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)config_setting_get_string_elem((struct config_setting_t const *)arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1int_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int arg3 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (config_setting_t *)config_setting_set_int_elem(arg1,arg2,arg3);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1int64_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  long long arg3 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (long long)jarg3; 
  result = (config_setting_t *)config_setting_set_int64_elem(arg1,arg2,arg3);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1float_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  double arg3 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  result = (config_setting_t *)config_setting_set_float_elem(arg1,arg2,arg3);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1bool_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  int arg3 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (config_setting_t *)config_setting_set_bool_elem(arg1,arg2,arg3);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1string_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (config_setting_t *)config_setting_set_string_elem(arg1,arg2,(char const *)arg3);
  *(config_setting_t **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (int)config_setting_index((struct config_setting_t const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1length(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  result = (int)config_setting_length((struct config_setting_t const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  unsigned int arg2 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (config_setting_t *)config_setting_get_elem((struct config_setting_t const *)arg1,arg2);
  *(config_setting_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1get_1member(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (config_setting_t *)config_setting_get_member((struct config_setting_t const *)arg1,(char const *)arg2);
  *(config_setting_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (config_setting_t *)config_setting_add(arg1,(char const *)arg2,arg3);
  *(config_setting_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1remove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)config_setting_remove(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1remove_1elem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)config_setting_remove_elem(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1setting_1set_1hook(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  config_setting_set_hook(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (config_setting_t *)config_lookup((struct config_t const *)arg1,(char const *)arg2);
  *(config_setting_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1from(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  config_setting_t *arg1 = (config_setting_t *) 0 ;
  char *arg2 = (char *) 0 ;
  config_setting_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_setting_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (config_setting_t *)config_lookup_from(arg1,(char const *)arg2);
  *(config_setting_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (int)config_lookup_int((struct config_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1int64(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  long long *arg3 = (long long *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(long long **)&jarg3; 
  result = (int)config_lookup_int64((struct config_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 = (double *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  result = (int)config_lookup_float((struct config_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1bool(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (int)config_lookup_bool((struct config_t const *)arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ca_uwaterloo_esg_rvtool_jni_libconfig_libconfigJNI_config_1lookup_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3) {
  jint jresult = 0 ;
  config_t *arg1 = (config_t *) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  char *temp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(config_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = &temp3; 
    *arg3 = 0;
  }
  result = (int)config_lookup_string((struct config_t const *)arg1,(char const *)arg2,(char const **)arg3);
  jresult = (jint)result; 
  {
    jstring jnewstring = NULL;
    if (arg3) {
      jnewstring = (*jenv)->NewStringUTF(jenv, *arg3);
    }
    (*jenv)->SetObjectArrayElement(jenv, jarg3, 0, jnewstring); 
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


#ifdef __cplusplus
}
#endif

